### ISSUE TITLE
Weird tooltip behavior when switch themes

### ISSUE THREAD

**Issue by lawvs** [dot-cafe/beam.cafe#12]
#### What is the current behavior?

![screenshot](https://user-images.githubusercontent.com/18554747/89726330-4c463900-da54-11ea-85fc-851836cc916e.gif)

#### What is the expected behavior?

When removing the `body.theme-transition { transition: all 0.3s !important; }` class, it will works normally.

#### Your environment:
```
Version (see about page): 1.1.0.4
Browser-version: Chrome 84
Operating-system: Windows 10
```

**Comment by Simonwep** [comment]
Unfortunately the `theme-transition` thingy only works on non-chromium based browsers [perfectly](https://stackoverflow.com/questions/61483591/strange-color-transition-behavior-in-chrome)... so I want to keep this as it looks pretty neat IMO ^^ 

It's definitely not best practice but I've just "fixed" the transition properties for the tooltip element in 5f63e9ba26372774f9d9786d82caafc35c2bbaea considering that reduced-motion features have not yet landed and this was the easiest solution 😅
