### ISSUE TITLE
Google Fonts Replacement

### ISSUE THREAD

**Issue by Caramon23** [dot-cafe/beam.cafe#5]
In order to improve the respect of the privacy of the users of the service, would it be possible to replace the Google fonts by another solution, even if it means hosting them directly on the site?

I avoid as much as possible to use this solution on the services I host and it's one of the first feedback I got about the instance of beam.cafe I set up.

**Comment by Simonwep** [comment]
Very good idea! 
Added in cf82054325fb6bf8bb75af01b71386a97cbc9bc2, available since `1.0.0.4` :)
