### ISSUE TITLE
Better Documentation for production setup

### ISSUE THREAD

**Issue by antoinebou13** [dot-cafe/beam.cafe#8]
Can you create better inscription for the build and deployment with the backend for a production environment? Also, that could help with (Docker Support)[https://github.com/dot-cafe/beam.cafe/issues/4]

**Comment by Simonwep** [comment]
Yeah, currently you'd have to manually follow the steps described in [bare-vps-setup](https://github.com/dot-cafe/beam.cafe.sh/blob/master/docs/bare-vps.md), it's also more focused on CD for what I decided to use things like [PM2](https://pm2.keymetrics.io/) - such things are probably redundant if there's docker support.

Currently all env-variables are hard-coded (such as the domain, websocket endpoint etc.) maybe we should move these to a `.env` file.
